project:
  type: website

website:
  title: "Health Data Sandbox"
  site-url: "https://hds-sandbox.github.io/healthdata-sandbox/"
  navbar:
    logo: /img/logo.png
    logo-href: http://hds-sandbox.github.io/
    background: primary
    right: 
      - icon: github
        href: https://github.com/hds-sandbox
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/ucph-heads/
        aria-label: LinkedIn
    left:
      - text: Home
        href: ./index.qmd
      - text: Access
        href: access/setup.qmd
      - text: Modules
        href: develop/ehr-intro.qmd
  sidebar:
    - title: "Modules"
      style: "docked"
      search: true
      contents:
        - section: "EHR"
          contents: 
            - develop/ehr-intro.qmd 
        - section: "Precision Medicine"
          contents: 
        - section: "Dynamic risk prediction"
          contents:
        # - section: "R for Data Science"
        #   contents:
        #     - href: https://center-for-health-data-science.github.io/R4DataScience/
        #       text: "R for Data Science Website" 
        - href: https://center-for-health-data-science.github.io/R4DataScience/
          text: "R for Data Science Website" 

copyright: CC-BY-SA 4.0 license

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true

filters:
  - css/custom-callout.lua
